### PR TITLE
Update nyc to latest

### PR DESCRIPTION
**Pull request by tandrewnichols**
Addresses #2

### CODE REVIEW

**Comment by aldex32** [comment]
Hi guys, is this going to be merged and published?

**Comment by tandrewnichols** [comment]
It could be merged/published anytime once it's confirmed that nothing is broken. The latest version of `nyc` is at a different major version number, which means there could be breaking changes, so I'm waiting for a chance to test it out (but you can help by pulling it in to your code as well).

**Comment by aldex32** [comment]
Hi @tandrewnichols ,

I did npm install of this branch, and `sonar nyc` seems to work properly!

**Comment by tandrewnichols** [comment]
Awesome, thanks for doing that. I guess the simplest thing might be to merge this and allow any problems to surface via bug reports.

**Comment by tandrewnichols** [comment]
Published as `2.0.0`.

**Pull request merged**
