### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tiagojsag**
Updated dependencies based on the output of `npm audit`. This did require bumping the dependency on NYC from v13 to v14, so if this does get merged, I would recommend reflecting this on the version number.

### CODE REVIEW

**Comment by tandrewnichols** [comment]
Hmm, that test failure is interesting. It says it can't find the codeclimate repo token, but . . . it's there in `.travis.yml`. I'm wondering if npm scripts do unusual things with environment variables that I've just never caught before.

**Comment by tandrewnichols** [comment]
Looks like maybe codeclimate changed how this works. Fun.

**Comment by tandrewnichols** [comment]
I pushed a branch called `debug-cc-token`, and the codeclimate coverage report is working in that. Try merging that into your branch to see if that fixes the issue.

**Comment by tiagojsag** [comment]
seems to have done the trick ;)

**Comment by tandrewnichols** [comment]
Thanks, @tiagojsag!

**Comment by tandrewnichols** [comment]
Published as `3.0.0`.

**Comment by tiagojsag** [comment]
thank you for the lib, happy to contribute :)

**Pull request merged**
